#!/usr/bin/env bash
set -euo pipefail

TEMPLATE=${1:-}
PORT=8050

SECRETS_CONF="${SHANKTOSECRETS:-~/va/shanktosecrets}/vistalink/vista-vm.conf"
if [ -z "${VISTA_ACCESS_CODE:-}" -a -f "$SECRETS_CONF" ]
then
  . "$SECRETS_CONF"
fi

test -n "$VISTA_ACCESS_CODE"
test -n "$VISTA_VERIFY_CODE"

usage() {
cat<<EOF

Perform envsubstitution on the given template then post it a locally running
server that assumes a VistA VM is also running.

${1:-}
EOF
exit 1
}

if [ -z "${TEMPLATE:-}" ]; then usage "template not specified"; fi
if [ ! -f "$TEMPLATE" ]; then usage "template not found: $TEMPLATE"; fi

shift

POST_ME=$(mktemp)
onExit() { rm $POST_ME; }
trap onExit EXIT

cat $TEMPLATE | envsubst > $POST_ME
if [ "${LOG_REQUEST:-false}" == true ]
then
  echo "REQUEST:"
  cat $POST_ME |  jq '.' | sed -e 's/"\(access\|verify\)Code":.*/"\1Code": "REDACTED"/'
fi

curl \
  -s \
  -XPOST \
  -H"Content-Type:application/json" \
  --data @$POST_ME \
  ${URL:-http://localhost:$PORT/rpc} \
  $@
