@startuml

|App|
start
:Search for coverage by patient;

|Vista-Fhir-Query|
:Convert request to RPC query;

|Charon API|
:Look up VistA instances for patient;

|MPI|
:""GetCorrespondingIDs"";

|Charon API|
while (For each VistA instance) is (vista)
  :Invoke RPC;
  |VistA|
  :Return RPC results;
  |Charon API|
  :Store intermediate result;
endwhile (done)
:Combine results from each RPC;

|Vista-Fhir-Query|
:Translate results to Fhir response;
:Return response;

|App|
stop

@enduml
